name: Claude Code Review
on:
  pull_request:
    types: [review_requested]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            Review this PR focusing on:
            - Security implications (OWASP patterns)
            - Performance considerations
            - Code quality and best practices
            Use mcp__github_inline_comment__create_inline_comment for specific issues.
