"""Pytest configuration and shared fixtures for JudicAIta tests."""

import logging
import sys
from pathlib import Path

import pytest

# Add src to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


@pytest.fixture(autouse=True)
def reset_logging() -> None:
    """Reset logging configuration for each test."""
    # Remove all handlers from all loggers
    loggers = [logging.getLogger()] + list(logging.Logger.manager.loggerDict.values())
    for logger in loggers:
        if isinstance(logger, logging.Logger):
            logger.handlers = []
            logger.setLevel(logging.NOTSET)


@pytest.fixture
def sample_legal_text() -> str:
    """Sample legal text for testing."""
    return """
    SETTLEMENT AGREEMENT

    This Settlement Agreement ("Agreement") is entered into as of January 1, 2024,
    by and between Acme Corporation ("Party A") and Widget Industries ("Party B").

    WHEREAS, the parties wish to settle all disputes arising from Contract No. 12345;

    NOW, THEREFORE, in consideration of the mutual covenants and agreements contained
    herein, the parties agree as follows:

    1. TERMINATION: This agreement may be terminated by either party with 30 days
    written notice.

    2. INDEMNITY: Each party shall indemnify and hold harmless the other party from
    any and all claims arising from its own negligence.

    3. GOVERNING LAW: This Agreement shall be governed by the laws of the State of
    California.

    IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first
    written above.
    """


@pytest.fixture
def sample_contract_dict() -> dict:
    """Sample contract data structure."""
    return {
        "parties": ["Acme Corporation", "Widget Industries"],
        "effective_date": "2024-01-01",
        "clauses": {
            "termination": "30 days written notice",
            "indemnity": "Each party indemnifies the other",
            "governing_law": "State of California",
        },
        "contract_number": "12345",
    }


@pytest.fixture
def sample_case_citation() -> str:
    """Sample legal case citation in Bluebook format."""
    return "Brown v. Board of Educ., 347 U.S. 483 (1954)"


@pytest.fixture
def sample_pdf_path(tmp_path: Path) -> Path:
    """Create a temporary PDF file path for testing."""
    pdf_path = tmp_path / "test_contract.pdf"
    # Note: Actual PDF content would need to be generated by tests that use this
    return pdf_path


# ==================== PYTEST CONFIGURATION ====================


def pytest_configure(config: pytest.Config) -> None:
    """Configure pytest with custom markers."""
    config.addinivalue_line("markers", "unit: Unit tests (fast, isolated)")
    config.addinivalue_line(
        "markers", "integration: Integration tests (moderate speed, multiple components)"
    )
    config.addinivalue_line("markers", "e2e: End-to-end tests (slow, full workflows)")
    config.addinivalue_line("markers", "tpu: Tests requiring TPU access")
    config.addinivalue_line("markers", "slow: Slow tests (>5 seconds)")
    config.addinivalue_line("markers", "kaggle: Tests specific to Kaggle environment")


def pytest_collection_modifyitems(config: pytest.Config, items: list) -> None:
    """Automatically mark tests based on their location."""
    for item in items:
        # Auto-mark tests based on directory
        if "unit" in str(item.fspath):
            item.add_marker(pytest.mark.unit)
        elif "integration" in str(item.fspath):
            item.add_marker(pytest.mark.integration)
        elif "e2e" in str(item.fspath):
            item.add_marker(pytest.mark.e2e)

        # Mark slow tests
        if "slow" in item.nodeid:
            item.add_marker(pytest.mark.slow)
